---
- name: Install Http server
  hosts: n6
  become: yes

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start Httpd
      service:
        name: httpd
        state: started

    - name: Enable Httpd
      service:
        name: httpd
        enabled: yes

- name: Tasks for n5
  hosts: n5
  tasks:
    - name: Install Apache2
      yum:
        name: apache2
        state: present

    - name: Start Apache2
      service:
        name: apache2
        state: started

    - name: Enable Apache2
      service:
        name: apache2
        enabled: yes

- name: Tasks for n7
  hosts: n7
  tasks:
    - name: Install HTTPD on CentOS
      yum:
        name: httpd
        state: present

    - name: Start Httpd on CentOS
      service:
        name: httpd
        state: started

    - name: Enable Httpd on CentOS
      service:
        name: httpd
        enabled: yes
...


