---
- name: Install Http server
  hosts: g3
  become: yes

  tasks:
  hosts: n6
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start Httpd
      service:
        name: httpd
        state: started

    - name: Enable Httpd
      service:
        name: httpd
        enabled: yes 

tasks:
  hosts: n5
    - name: Install Apache2
      yum:
        name: apache2
        state: present

    - name: Start Apache2
      service:
        name: apache2
        state: started

    - name: Enable Apache2
      service:
        name: apache2
        enabled: yes

tasks:
  hosts: n7
    - name: Install HTTPD on CentOS
      yum:
        name: httpd
        state: present

    - name: Start Httpd on CentOS
      service:
        name: httpd
        state: started

    - name: Enable Httpd on CentOS
      service:
        name: httpd
        enabled: yes
...


