- name: Install and Configure HTTP Server
  hosts: g2
  become: yes
  tasks:
    - name: Install HTTPD on Amazon Linux
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install HTTPD on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start and Enable HTTP Service
      service:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS' else 'apache2' }}"
        state: started
        enabled: yes
...


